export const profile = {
  name: "Swathiga",
  linkedin: "https://www.linkedin.com/in/swathiga-b-0a54b2157",
  resume: "https://57108228-8895-40b7-90ac-ffe06cfbb2cb.filesusr.com/ugd/4d683e_d860bc40e0934131a72f7dc4233234dd.pdf",
};
export type Project = { name: string; category: string; description: string; tags: string[]; url?: string; image?: string; logo?: boolean; color: string; number: string; platform?: string; };
export const projects: Project[] = [
  {name:"GenieMX",image:"/images/geniemx-logo.svg",logo:true,category:"AI & document intelligence",platform:"Web / AI",description:"A RAG application with a custom document parsing pipeline, scoped retrieval, and document Q&A. Built with Python, FastAPI, PostgreSQL/pgvector, Cloudflare R2, and Celery workers backed by Redis. Deployed on an Ubuntu VPS with Coolify.",tags:["Python","FastAPI","RAG","pgvector","Celery"],url:"https://geniemx.matevix.com",color:"blue",number:"08"},
  {name:"The Lookout",category:"Discovery & lifestyle",description:"Brand and product discovery with gesture-driven interactions, searchable collections, and an events calendar. Contributions spanned application design, Firebase login, Algolia search, and background processing.",tags:["iOS","Firebase","Algolia","GCD"],url:"https://apps.apple.com/in/app/the-lookout/id1599489015",image:"/images/project-1.jpg",color:"lilac",number:"01"},
  {name:"Consulta",category:"Healthcare",description:"Connecting families with care through health reports, online and hospital appointments, Twilio chat, and payment features. Work included code maintenance and version updates.",tags:["iOS","Twilio","Apple Pay"],url:"https://apps.apple.com/in/app/consulta/id1522423346",image:"/images/project-2.jpg",color:"mint",number:"02"},
  {name:"Crew Pass",category:"Maritime",description:"An app for crew, agencies, and vessels, with role-based experiences, chat, date-range selection, and Bluetooth-enabled onboarding and offboarding. Contributions included maintenance and version updates.",tags:["iOS","Bluetooth","Chat"],url:"https://apps.apple.com/in/app/crewpass/id1579634657",image:"/images/project-3.jpg",color:"blue",number:"03"},
  {name:"SRH-Connect",image:"/images/project-4.jpg",category:"Healthcare",description:"A patient-facing appointment app. Owned the application journey from App Store account setup through release and ongoing maintenance.",tags:["iOS","Firebase","App Store"],url:"https://apps.apple.com/in/app/srh-connect/id6446798097",color:"peach",number:"04"},
  {name:"SRH-DRMS",image:"/images/project-5.jpg",category:"Healthcare",description:"Patient referrals for doctors and staff, with multiple login roles and customized graph interfaces.",tags:["iOS","Data visualization","Firebase"],url:"https://apps.apple.com/in/app/srh-drms/id6466620577",color:"mint",number:"05"},
  {name:"Health Basix",image:"/images/project-6.jpg",category:"Healthcare",description:"School healthcare with secure login, downloadable health reports, and appointment features. Contributions included code maintenance and version updates.",tags:["iOS","Authentication","Healthcare"],url:"https://apps.apple.com/in/app/health-basix/id1595269357",color:"lilac",number:"06"},
  {name:"Care Station",image:"/images/project-7.jpg",category:"Healthcare",description:"A school-clinic app for nurses to manage treatment forms, attendance, and inventory. Core Data supports offline form editing. Distributed as an unlisted application.",tags:["iOS","Core Data","Offline storage"],color:"blue",number:"07"},
];
