import reviewmind from "./reviewmind.json";
export type PostSection = {title:string;paragraphs:string[];code?:string;images?:{src:string;alt:string}[]};
export type Post = {slug:string;title:string;category:string;summary:string;readTime:string;sections:PostSection[];status?:string;artLabel?:string;artText?:string;repository?:string};
export const posts:Post[]=[
 reviewmind,
 {slug:"building-a-rag-parsing-pipeline",title:"Building a custom document parsing pipeline for RAG",category:"AI & ENGINEERING",summary:"What I learned about document routing, parser fallbacks, chunking, and quality checks while building a RAG application.",readTime:"4 min read",sections:[
  {title:"From iOS to RAG",paragraphs:["After working in iOS development, I wanted to explore AI by building a RAG application. One of the first challenges was document parsing: missing tables, broken reading order, and incomplete text can affect both retrieval and the answers generated later.","A single parsing library did not handle all my documents consistently. I built a custom pipeline in Python and FastAPI, with PostgreSQL and pgvector for storage and retrieval."]},
  {title:"1. Identify and prepare the document",paragraphs:["Each document receives an ID and metadata including its original filename, client ID, matter ID, and Cloudflare R2 object key. These fields connect extracted content to its source and retrieval scope.","The pipeline receives file bytes and writes a temporary copy with the original extension for parsers that expect a file path. A finally block removes that copy after processing; the original stays in R2."]},
  {title:"2. Route and parse",paragraphs:["For supported non-PDF formats, I use Docling with format-specific fallbacks such as python-docx, python-pptx, and openpyxl. Images and content requiring visual interpretation can go to a vision-language model.","PDFs follow a separate pipeline. I start with PyMuPDF for lightweight extraction, use Docling when extraction is insufficient, pdfplumber for tables, and a VLM for pages requiring visual interpretation. The extracted blocks are assembled in page order.","Combining parsers also introduces a challenge: preventing duplicate content and preserving reading order. The routing and assembly logic matters as much as the libraries themselves."]},
  {title:"3. Chunk the extracted content",paragraphs:["The parsed document passes to chunk_document(). This prepares smaller units for retrieval while retaining client and matter scope. Boundaries matter: a heading separated from its explanation or a table separated from its context becomes harder to interpret.","Keeping chunking separate from parsing lets me improve either stage independently."]},
  {title:"4. Score before indexing",paragraphs:["Heuristic checks look at word count, headings without supporting content, and expected table formatting. They flag weak extraction; they do not prove that the text is correct.","Each chunk is selected for automatic embedding, returned for review, or dropped from automatic indexing. The function collects review candidates; a persistent review workflow is a separate feature."]},
  {title:"5. Store accepted chunks",paragraphs:["Accepted chunks pass to the storage layer. The indexing flow stores text, metadata, and searchable embeddings in PostgreSQL with pgvector.","The result reports stored, review, and dropped chunk counts, fallback pages, and storage errors. Finishing parsing is not always the same as being searchable: a document can produce no accepted chunks, or indexing can fail."],code:"parsed_doc = route_and_parse(\n    doc_id=raw_doc.doc_id,\n    file_path=temp_file_path,\n    source_type=source_type,\n    fallback_parser=fallback_parser,\n    model=model,\n    api_key=api_key,\n)\n\nchunks = chunk_document(\n    parsed_doc, client_id=client_id, matter_id=matter_id\n)\nscores = {s.chunk_id: s for s in score_chunks(chunks)}\naccepted = [\n    chunk for chunk in chunks\n    if scores[chunk.chunk_id].decision\n    == ReviewDecision.AUTO_EMBED\n]\nchunks_stored = store_chunks(accepted) if accepted else 0"},
  {title:"What I learned",paragraphs:["Inspect intermediate results instead of judging parsing only by the final chatbot answer. Extracted blocks, chunk boundaries, fallback decisions, and rejected chunks each reveal different problems.","My next step is to evaluate representative documents and questions so I can measure how extraction changes affect retrieval and answers."]}
 ]},
 {slug:"deploying-with-coolify",title:"Setting up my Ubuntu server with Coolify",category:"DEPLOYMENT",summary:"Taking my RAG application from a local project to a Hostinger VPS, with GitHub deployments and a simpler way to manage configuration.",readTime:"3 min read",sections:[
  {title:"From a local pipeline to a server",paragraphs:["After building my RAG parsing pipeline, I deployed it using Coolify on a Hostinger VPS running Ubuntu. Coolify is an open-source deployment platform that runs applications in Docker containers.","It helped me manage deployments, environment variables, and logs from one dashboard."]},
  {title:"1. Install Coolify",paragraphs:["I connected to my Ubuntu VPS through SSH, then ran the official installer as root. Run these commands on the server itself, not inside an application container.","After installation, open the dashboard address printed in the terminal and create the admin account. Check the current Coolify installation guide for supported systems and prerequisites."],code:"ssh root@YOUR_SERVER_IP\n\ncurl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash\n\n# For a non-root user with sudo access:\n# curl -fsSL https://cdn.coollabs.io/coolify/install.sh | sudo bash"},
  {title:"2. Connect GitHub",paragraphs:["Push the application to GitHub. Configure a GitHub App connection in Coolify, grant access to the repository, and create an application resource inside a project and environment.","Select the branch, server, and destination network. With automatic deployment enabled and the integration configured, a push to the selected branch can trigger a deployment."]},
  {title:"3. Configure the build",paragraphs:["I selected Nixpacks for my Python backend, checked the base directory and dependency installation, and set the start command.","For a FastAPI instance named app in app/main.py, bind Uvicorn to 0.0.0.0 and match the internal port in Coolify. Leave --reload for local development."],code:"uvicorn app.main:app --host 0.0.0.0 --port 8000"},
  {title:"4. Add runtime configuration",paragraphs:["Add the database connection and provider credentials in the application's environment settings. Keep secrets available at runtime; enable build-time access only if the build needs them.","Configure a domain for the public API, save the settings, and deploy. Separate Celery worker applications use the same repository with a Celery start command and connect to the same Redis instance through its internal URL."]},
  {title:"5. Follow the right logs",paragraphs:["Deployment and build logs show dependency installation or container image failures. Runtime logs show startup exceptions, failed connections, and request errors after the application starts.","Once the initial setup was complete, Coolify brought my repository integration, configuration, and logs together, making updates easier to manage through Git."]}
 ]}
];
